### ISSUE TITLE
Rocolatey is unable to detect outdated packages from Chocolatey Community Repostiory

### ISSUE THREAD

**Issue by chakbabura** [rocolatey/rocolatey#221]
I am using the following versions:
- Chocolatey v2.2.2
- Rocolatey v0.8.2

Recently, rocolatey is unable to detect outdated chocolatey packages & is failing with the following error:
```
failed to fetch packages: failed to receive packages from NuGet v2 feed 'https://community.chocolatey.org/api/v2/'
```
This can can be seen from the below screenshot:
<img width="822" alt="outdated" src="https://github.com/rocolatey/rocolatey/assets/25573604/bb1c7969-f2e0-4e24-bb85-050f06a99a8e">

To investigate further I did the following:
- I executed the `roco outdated -v` to get verbose output which gave the following result (partial screenshot below):
<img width="1097" alt="outdated-verbose" src="https://github.com/rocolatey/rocolatey/assets/25573604/36fbbb99-d2ac-40c9-beac-41c93991add5">
- Upon making the API call with the link from the above screenshot, I found the following result:
<img width="1105" alt="choco-api" src="https://github.com/rocolatey/rocolatey/assets/25573604/be7d5d21-6592-46f2-bcfe-2bfe2b4f8b1c">
- This, finally, led me to this link: [Chocolatey API Changes](https://blog.chocolatey.org/2024/03/ccr-api-changes/#api-changes). As far as I understand from this, filtering options are only allowed now using chocolatey CLI & associated library.

Please let me know in case of any further info.

**Comment by mwallner** [comment]
Hey,
Thanks for creating this issue, I'm unfortunately already aware of this.

Rocolatey 0.9 should be ready be the end of this week, stay tuned!

NOTE though: roco 0.9 will be able to check for outdated packages with the community repo, but the main performance benefit will be gone / so unless you're using other feeds also, you might be better of just using choco.exe itself.

**Comment by chakbabura** [comment]
Thanks for the update @mwallner.
Its unfortunate to see the support for filtering using API calls being removed from the Chocolatey API.
Hopefully, this change gets reverted or a workaround is found soon.
Love the rocolatey project nonetheless.

**Comment by asheroto** [comment]
Looking forward to the update!

**Comment by mwallner** [comment]
same here, hopefully will get the time this afternoon though 😉

**Comment by mwallner** [comment]
working on it, version 0.9 isn't going to be awesome in terms of performance, but probably as good as can be without caching.

![flamegraph](https://github.com/rocolatey/rocolatey/assets/5354972/7c6dd5c1-e22f-4033-b13d-df54513a71bd)

**Comment by mwallner** [comment]
[roco 0.9](https://github.com/rocolatey/rocolatey/releases/tag/v09.0) has been released - it'd be great if you could give it a try and report if you have any issues with it.

thanks ~

**Comment by chakbabura** [comment]
Thanks for the update @mwallner.
Although the above issue is fixed, it came at a significant performance cost (as previously predicted).
Hopefully, the API endpoint gets modified in the future to workaround this.
Nonetheless, thanks for the great work. 😃
